### ISSUE TITLE
nix flakes

### ISSUE THREAD

**Issue by x10an14** [n8henrie/nixos-btrfs-pi#1]
Hi!

I've been trying to do the same as you the last couple of days (raspberry pi 3b+ with nixos on btrfs).

I'm wondering if you're interested in looking into converting this set-up to a `flake.nix`'s output?

That way, it'd be easier for folk (like me) to both build the sdImage, but also use tools like `deploy-rs` later (on top of syncing config in a repo with other machines using the same `flake.nix`).

**Comment by n8henrie** [comment]
Hi -- thanks for reaching out.

As I'm sure you can tell, I'm very new to nix and nixos. I have just
started reading about flakes and have no idea how to create or use one.

Contributions are welcome!

Also, if you have any idea how to get it to boot from a compressed
subvolume, I'm still struggling here!

**Comment by x10an14** [comment]
> Contributions are welcome! 

If I can think of anything useful, I will =) For now I'm just trying to "frankenstein" your scripts/setup to match my desired config.
(I don't want compressed subvols for instance, I want that data checksumming and copy-on-write).

So far I haven't managed to get this to work with nix flakes, but what I'm trying to do is to make this config reference my flaked machine-specific config.

So that I can get the best of both worlds, a flake with my system's config, and some scripts (plus some of your *.nix files) to create the SD-Card image in the first place.

**Comment by n8henrie** [comment]
Got a flake working. That was a learning experience for sure.
