### ISSUE TITLE
Pi 4 support

### ISSUE THREAD

**Issue by foxidokun** [n8henrie/nixos-btrfs-pi#2]
Hi!

I'm not a Nix expert so I can't do it myself, but I think it's a good idea to add configuration option (raspi version switch) for raspberry pi 4 support (or just mention in readme). Configurations differ only on this [line](https://github.com/n8henrie/nixos-btrfs-pi/blob/master/nixos/hardware-configuration.nix#L25) (changing 3 to 4 made your configuration work on rpi 4)

Also, on Arch Linux nix from community repo requires `--extra-experimental-features nix-command` to work (see [this](https://github.com/NixOS/nixpkgs/issues/80332))

**Comment by foxidokun** [comment]
Okay, actually it doesn't work (yet). I can boot with generated nixos-btrfs.img, but after `nixos-install` (or just `nixos-rebuild`) & reboot, with almost the same configuration as the nixos-btrfs.img was built with, it freezes on line `Starting kernel...`


[configs.tar.gz](https://github.com/n8henrie/nixos-btrfs-pi/files/8374050/config.tar.gz)

**Comment by n8henrie** [comment]
Hi -- thanks for your thoughts!

I don't have a spare RPi 4 for testing, so I haven't included relevant config. Perhaps I'll mention it in the readme.

And yes, thanks for the mention of the extra config required for the `nix` command, I forgot that I'd set that up.

**Comment by n8henrie** [comment]
I'm going to close as I still don't have a spare Pi 4 and still have work to do on the 3.

**Comment by n8henrie** [comment]
@foxidokun I just got around to trying this today. By adding the same overlay to uboot pi 4 as I had already done for uboot pi 3, everything seemed to work -- booted the resulting image on a Pi4 and got to a login prompt.

**Comment by n8henrie** [comment]
Well, it boots from an SD card at least. Not working from USB drive yet, not sure why.

**Comment by n8henrie** [comment]
Was able to get a working USB boot by adding `all-hardware.nix` to the imported modules: 

https://github.com/NixOS/nixpkgs/issues/122130#issuecomment-845572962

**Comment by foxidokun** [comment]
It is very good news! Were you able to install anything with nixos-rebuild and successfully reboot after?

**Comment by n8henrie** [comment]
> Were you able to install anything with nixos-rebuild and successfully reboot after?

Yes, it seems to be working well. As I mentioned [here](https://github.com/NixOS/nixpkgs/issues/122130#issuecomment-1568815007), I manually boiled down `all-hardware.nix` to what seems to be the 3 essential kernel modules:

```nix
boot.initrd.kernelModules = ["zstd" "btrfs"];
boot.initrd.availableKernelModules = [
        "uas"
        "pcie-brcmstb"
        "reset-raspberrypi"
      ];
```

Of note, importing the pi4 settings from [`nixos-hardware`](https://github.com/NixOS/nixos-hardware/tree/master/raspberry-pi/4) *prevents* it from being able to boot, which is frustrating -- not sure why.
